Algoritmo "Matriz_Ex_2"

Var

   x : vetor[0..1, 0..1] de inteiro
   i, j : inteiro
Inicio


//entrada de dados
      para i de 0 até 1 faça
        para j de 0 até 1 faça
          escreva("Valor: ")
          leia(x[i,j])
        fimpara
      fimpara

      //saída de dados
      para i de 0 até 1 faça
        para j de 0 até 1 faça
            escreval(x[i,j])
        fimpara
      fimpara
      
fimalgoritmo