 algoritmo "numeromaior"

 var

      a, b:real
      

 inicio

      escreval("Escreva valor de a: ")
      leia(a)
      
      escreval("Escreva valor de b: ")
      leia(b)
      
      se a > b entao
         escreval("a é maior que b")
         senão
           se b > a entao
               escreval("b é maior que a")
           senao
                 escreval("a e b são iguais")
      fimse
           fimse
 fimalgoritmo