algoritmo "exercicio05"

var

   a, b, soma, subtracao, multiplicacao, divisao: real

inicio

   escreval("Digite um numero: ")
   leia(a)
   
   escreval("Digite um numero: ")
   leia(b)
   
   soma<- a + b
   
   subtracao<- a - b
   
   multiplicacao<- a * b
   
   divisao<- a / b
   
   escreval ("Soma=  ", soma)
   escreval ("Subtracao= ", subtracao)
   escreval ("Multiplicacao= ", multiplicacao)
   escreval ("Divisao= ", divisao)

fimalgoritmo